### ISSUE TITLE
Provide instructions how to install the libraries used by NativeCall

### ISSUE THREAD

**Issue by antononcube** [bduggan/p6-digest-sha256-native#4]
I cannot install this package on macOS. (And because of that cannot use ["Jupyter::Kernel"](https://github.com/bduggan/p6-jupyter-kernel).)

Please provide instructions how to make and/or install the required C libraries. (Ideally, for Linux, macOS, and Windows 10.)

**Comment by bduggan** [comment]
What happens when you run `zef install -v Digest::SHA256::Native`?

**Comment by bduggan** [comment]
interesting...
```
(mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))
```
As far as library dependencies, there shouldn't be much, the [code](https://github.com/bduggan/p6-digest-sha256-native/blob/master/src/sha256.c) just uses standard libraries.

Can you try cloning the git repo, and just running `raku Configure.pl6`?  It seems like perhaps the compiler isn't generating the right kind of object file?

**Comment by antononcube** [comment]
I cloned the repository, run "Config.pl6", and run `zef install .`: 

```
[15:42]bduggan/p6-digest-sha256-native> raku Configure.pl6                    
clang -dynamiclib  -O3 -DNDEBUG -Wl,-rpath,@executable_path/../lib -o ./resources/libraries/libsha256.dylib sha256.o

[15:42]bduggan/p6-digest-sha256-native> zef install .                         
===> Building: Digest::SHA256::Native:ver<0.04>
===> Building [OK] for Digest::SHA256::Native:ver<0.04>
===> Testing: Digest::SHA256::Native:ver<0.04>
[Digest::SHA256::Native] Cannot locate native library '/Users/boss2/GitHub/bduggan/p6-digest-sha256-native/resources/libraries/libsha256.dylib': dlope
[Digest::SHA256::Native] n(/Users/boss2/GitHub/bduggan/p6-digest-sha256-native/resources/libraries/libsha256.dylib, 0x000A): tried: '/var/folders/j5/vnk_my8d2r36k6tnsvn92wvr0000gn/T//par-616e746f6e6f76/cache-3c736d7a8c15ba9ac5e363ba7a524ca2d46d7b51/libsha256.dylib' (no such file
[Digest::SHA256::Native] ), '/Users/boss2/GitHub/bduggan/p6-digest-sha256-native/resources/libraries/libsha256.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
[Digest::SHA256::Native]   in method setup at /Users/boss2/.rakubrew/versions/moar-/share/perl6/core/sources/A37F26876B58371B70EDD889AD69F064C90AC2C6 (NativeCall) line 319
[Digest::SHA256::Native]   in method setup at /Users/boss2/.rakubrew/versions/moar-/share/perl6/core/sources/A37F26876B58371B70EDD889AD69F064C90AC2C6 (NativeCall) line 366
[Digest::SHA256::Native]   in sub raku-nativecall at /Users/bo
[Digest::SHA256::Native] ss2/.rakubrew/versions/moar-/share/perl6/core/sources/A153F63283BF744FD66BF7212910E5F389384F6E (NativeCall::Dispatcher) line 46
[Digest::SHA256::Native]   in sub sha256-hex at /Users/boss2/GitHub/bduggan/p6-digest-sha256-native/lib/Digest/SHA256/Native.pm6 (Digest::SHA256::Native) line 19
[Digest::SHA256::Native]   in sub sha256-hex at /Users/boss2/GitHub/bduggan/p6-digest-sha256-native/lib/Digest/SHA256/Native.pm6 (Digest::SHA256::Native) line 10
[Digest::SHA256::Native]   in block <unit> at t/01-basic.t line 6
[Digest::SHA256::Native] 
===> Testing [FAIL]: Digest::SHA256::Native:ver<0.04>
Aborting due to test failure: Digest::SHA256::Native:ver<0.04> (use --force-test to override)
```

**Comment by bduggan** [comment]
From the `arm64e` error -- I'm guessing perhaps this is an M1 and the compiler needs some extra flags of some sort.

I see some ideas in this [article](https://iraspa.org/blog/compiling-for-the-apple-m1/) ...

maybe try `export CCFLAGS="-target arm64-apple-macos11 -mmacosx-version-min=11.0"` first?

**Comment by antononcube** [comment]
You suggestion worked. Here are the steps on my computer with macOS 12.5.1 :

1. Clone the repository
2. (Try to) install the repository's package with `zef install .`
   - And that fails.
3. Remove the file "resources/libraries/libsha256.dylib"
4. Execute the command `export CCFLAGS="-target arm64-apple-macos12 -mmacosx-version-min=12.0"` 
5. Install the package with `zef install .`

**Comment by bduggan** [comment]
Great!

**Comment by antononcube** [comment]
> Great!

I still think you should put that in some sort of installation documentation. :)

BTW, I managed to install "Jupyter::Kernel". 
This GiHub directory has both Python and Raku Jupyter notebooks with (Raku-based) DSL generation examples over common data wrangling workflows: https://github.com/antononcube/RakuForPrediction-book/tree/main/Notebooks/Jupyter .

**Comment by bduggan** [comment]
I'm going to go ahead and close this -- hopefully this ticket can be used for reference for anyone else who runs into this.  If it seems to be common I can add it to the README -- but it seems like this is more of a platform-specific issue that would affect compilation of a lot of things on an M1.
